language: minimal
os: linux
dist: bionic
addons:
    apt:
        sources:
            - docker-bionic
services:
    - docker

env:
    - BASE=alpine
    - BASE=ubuntu
script:
    - docker build -t "corysanin/openrct2-ffa:$TRAVIS_BRANCH-$BASE" -f ./dockerfiles/ffa/$BASE/Dockerfile .
after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - if [ "$TRAVIS_PULL_REQUEST" = false ]; then docker push "corysanin/openrct2-ffa:$TRAVIS_BRANCH-$BASE"; fi
