version: '3'

services:

    openrct2-saveprep:
        container_name: openrct2-saveprep
        build:
            context: ./
            dockerfile: ./Dockerfile
        ports:
            - 8080:8080
