version: '3'

services:

    openrct2-saveprep:
        container_name: openrct2-saveprep
        build:
            context: ./
            dockerfile: ./Dockerfile
        ports:
            - 8080:8080
        volumes:
            - $RCT2PATH:/rct2:ro
            - $RCT1PATH:/rct1:ro
            - /etc/localtime:/etc/localtime:ro
